### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by AusNBNCO** [MrCoolAndroid/Xbox-Rich-Presence-Discord#12]
Still crashes

**Comment by MrCoolAndroid** [comment]
Hello @AusNBNCO, can you provide more information? Where it crashes, is there any error, etc

**Comment by AusNBNCO** [comment]
It Crashes after logging in when choosing the console

**Comment by MrCoolAndroid** [comment]
Are you using the latest version? Do you open the Discord app before starting the app? And just in case, what console is it?

**Comment by AusNBNCO** [comment]
I am using the latest version my discord was open before opening the program and I use both a 360 and a xbox one

**Comment by MrCoolAndroid** [comment]
Okay, thanks for your feedback, i will check for any errors today if I can

**Comment by MrCoolAndroid** [comment]
This issue should be fixed (when the API is back to normal) with this [release](https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/tag/v0.5.5-beta)
