### ISSUE TITLE
I go to log in and it crashes

### ISSUE THREAD

**Issue by JustAssassinExists** [MrCoolAndroid/Xbox-Rich-Presence-Discord#4]
I log in with my Gamertag and API key and it just crashes

**Comment by JustAssassinExists** [comment]
Windows 10 Pro 
21H2

**Comment by MrCoolAndroid** [comment]
@JustAssassinExists Are you using the [latest release?](https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/tag/v0.5.3.3-beta)

**Comment by MrCoolAndroid** [comment]
@JustAssassinExists I might close the issue if I don't have further info

**Comment by JustAssassinExists** [comment]
Sorry, yes I am using the latest release

**Comment by MrCoolAndroid** [comment]
@JustAssassinExists Be sure to check the latest release again, i updated it yesterday or so, with a new setup, if you downloaded that one, what is your gamertag? Does it have any especial characters? Or what game were you playing in the time of trying the app?

**Comment by JustAssassinExists** [comment]
No I don’t think I had any special characters in my username, but I was playing Minecraft: Story Mode for Xbox 360

**Comment by MrCoolAndroid** [comment]
When opening the app do you get the "New update available" message? If not, were you a new user? Or you were using this app before

**Comment by JustAssassinExists** [comment]
I don’t get a new update message, but I am a new user yes

**Comment by MrCoolAndroid** [comment]
My bad.
@JustAssassinExists

**Comment by JustAssassinExists** [comment]
Yes I did

**Comment by MrCoolAndroid** [comment]
Alright then, when I get home I will check the app for any issues, if it haves one related to your issue i will update the app and let you know, thanks.

**Comment by JustAssassinExists** [comment]
Thank you dude

**Comment by JustAssassinExists** [comment]
I think I found my issue;

When I launch the app with my Xbox off it says
"Online: Windows 10"
but when I open the Xbox it crashes. I think it thinks I'm online on an app called "Windows 10" for some reason

**Comment by MrCoolAndroid** [comment]
@JustAssassinExists That is because you are online on Windows, for some reason it's reading the Windows 10 status, try not opening the Xbox Game Bar or any Windows Xbox Live Game and try with the Xbox 360 alone.
I think i know what's the issue, thanks for your info.

**Comment by MrCoolAndroid** [comment]
Normally when Windows is booted up if u dont open Game Bar it shouldnt sign in to Xbox Live

**Comment by JustAssassinExists** [comment]
It automatically does for me, it’s an auto open app because I use gamebar all the time

**Comment by JustAssassinExists** [comment]
I’ll close it and try again

**Comment by MrCoolAndroid** [comment]
@JustAssassinExists I have found the issue, an update is cooming in a bit, thanks for your help.

**Comment by MrCoolAndroid** [comment]
Hello @JustAssassinExists, this bug should be fixed with [this update](https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/tag/v0.5.4-beta), if you have any more errors or if it stills doesnt work for you, open another issue, thanks for your help.

**Comment by JustAssassinExists** [comment]
Can confirm that this works, thanks for your help too. I'll look out for bugs when I see them
