### ISSUE TITLE
Gears of War Malfunction

### ISSUE THREAD

**Issue by LieutenantSugar** [MrCoolAndroid/Xbox-Rich-Presence-Discord#59]
The presence crashes every time it refreshs to load any Gears of War game.

This was addressed in #46 but the issue still stands, even after the pull request was merged.

**Comment by MrCoolAndroid** [comment]
I will look into it, I am making a new update to fix a bunch of stuff and it will be a complete remake (just with the same design) and it should have less errors

**Comment by MrCoolAndroid** [comment]
It should now be fixed with the latest [release](https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/tag/v0.5.8-beta)
