### ISSUE TITLE
Need to install .NET, when I already have it installed.

### ISSUE THREAD

**Issue by DexrnZacAttack** [MrCoolAndroid/Xbox-Rich-Presence-Discord#77]
---------------------------
Xbox Discord Presence.exe
---------------------------
To run this application, you must install .NET.

Would you like to download it now?
---------------------------
Yes   No   
---------------------------

It doesn't even tell me what version, looking in the JSON file it says .NetCore 5.0, which I have installed, I even reinstalled it but it still gives me the same issue, pressing the Yes button does absolutely nothing.

**Comment by MrCoolAndroid** [comment]
This is a known bug, please try downloading [this](https://download.visualstudio.microsoft.com/download/pr/b6fe5f2a-95f4-46f1-9824-f5994f10bc69/db5ec9b47ec877b5276f83a185fdb6a0/windowsdesktop-runtime-5.0.17-win-x86.exe)

**Comment by DexrnZacAttack** [comment]
> This is a known bug, please try downloading [this](https://download.visualstudio.microsoft.com/download/pr/b6fe5f2a-95f4-46f1-9824-f5994f10bc69/db5ec9b47ec877b5276f83a185fdb6a0/windowsdesktop-runtime-5.0.17-win-x86.exe)

Worked!

**Comment by LieutenantSugar** [comment]
Reopening this as I'm getting this error as well. I installed the Runtime from the above solution, but I'm still getting the pop-up saying it needs .NET. Any suggestion as to what to do would be appreciated!

**Comment by MrCoolAndroid** [comment]
@LieutenantSugar Did you use the setup.exe version or the portable one?

**Comment by LieutenantSugar** [comment]
> @LieutenantSugar Did you use the setup.exe version or the portable one?

I used the EXE from the link you gave to DexrnZacAttack above. Should I use the portable one instead?

**Comment by MrCoolAndroid** [comment]
@LieutenantSugar Sorry for the late response, and sorry I meant the app's setup.exe or portable .zip on Releases. Although what you can try is installing the x64 runtime, let me see if I can find it

**Comment by LieutenantSugar** [comment]
> @LieutenantSugar Sorry for the late response, and sorry I meant the app's setup.exe or portable .zip on Releases. Although what you can try is installing the x64 runtime, let me see if I can find it

No worries. I downloaded the zip from [https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/tag/v0.6.0-beta](url) and extracted it into a folder, running "Xbox Discord Presence.exe" from within the folder. Hope that makes things clearer.

**Comment by MrCoolAndroid** [comment]
> > @LieutenantSugar Sorry for the late response, and sorry I meant the app's setup.exe or portable .zip on Releases. Although what you can try is installing the x64 runtime, let me see if I can find it
> 
> No worries. I downloaded the zip from https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/latest and extracted it into a folder, running "Xbox Discord Presence.exe" from within the folder. Hope that makes things clearer.

That's okay, can you try installing [this](https://download.visualstudio.microsoft.com/download/pr/3aa4e942-42cd-4bf5-afe7-fc23bd9c69c5/64da54c8864e473c19a7d3de15790418/windowsdesktop-runtime-5.0.17-win-x64.exe)?

**Comment by WifiRouterYT** [comment]
that worked for me on v0.6!

**Comment by MrCoolAndroid** [comment]
> that worked for me on v0.6!

That's awesome! I'll add it to the README then!

**Comment by LieutenantSugar** [comment]
> > > @LieutenantSugar Sorry for the late response, and sorry I meant the app's setup.exe or portable .zip on Releases. Although what you can try is installing the x64 runtime, let me see if I can find it
> > 
> > 
> > No worries. I downloaded the zip from https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/releases/latest and extracted it into a folder, running "Xbox Discord Presence.exe" from within the folder. Hope that makes things clearer.
> 
> That's okay, can you try installing [this](https://download.visualstudio.microsoft.com/download/pr/3aa4e942-42cd-4bf5-afe7-fc23bd9c69c5/64da54c8864e473c19a7d3de15790418/windowsdesktop-runtime-5.0.17-win-x64.exe)?

Yes! Worked for me as of 7/28/24. Thank you!

**Comment by MrCoolAndroid** [comment]
> Yes! Worked for me as of 7/28/24. Thank you!

Awesome @LieutenantSugar!, I will close this now
