### ISSUE TITLE
Error code 400 from playing Halo: MCC on PC

### ISSUE THREAD

**Issue by LOL-DUDE-64** [MrCoolAndroid/Xbox-Rich-Presence-Discord#86]
It worked fine on the main menu, but once I loaded into a Halo 3 Forge game on a modded map from the Workshop, it stopped working, and I got this message:

```
Error!

There was an error while
trying to connect to the
API! Response status code
does indicate success:
400 (Bad Request)
```

Pressing "OK" on this prompt just caused it to display again.

**Comment by MrCoolAndroid** [comment]
Does it only happens with that game/game mode? Which options are you using? (Limit 150 requests, SteamGridDB, etc)
