### ISSUE TITLE
New Game images

### ISSUE THREAD

**Issue by Xbox360guy25** [MrCoolAndroid/Xbox-Rich-Presence-Discord#94]
Add my game image for Street Fighter Third Strike Online Edition. 
![55542](https://github.com/user-attachments/assets/2563b82a-d0c2-4dd4-9a3e-83f635c772f5)
 it's resolution is 1024x1024 as required.
Upscaled in sharpess and no loss of quality
This is the first in a few game images I will do,
Thx.

**Comment by MrCoolAndroid** [comment]
I don't have a server to upload these images, these must be uploaded to one first so they can be added as an URL on the [Games List](https://github.com/MrCoolAndroid/Xbox-Rich-Presence-Discord/blob/main/Games%20List.json)

**Comment by Xbox360guy25** [comment]
Nice job bro. I'll try looking at Remastered versions of images instead.
